### PR TITLE
fixed const factory constructor

### PR DESCRIPTION
**Pull request by vr19860507**
https://github.com/dart-lang/code_builder/issues/288

### CODE REVIEW

**Comment by vr19860507** [comment]
@googlebot I signed it!

**Review by matanlurey — APPROVED** [review]
Approved. I'll want to update the CHANGELOG and add a test, but otherwise LG.

**Comment by kevmoo** [comment]
@matanlurey – you going to land this?

**Comment by matanlurey** [comment]
I need to make edits to the CHANGELOG and add a test. I only typically do open source stuff on Fridays, sorry.

**Pull request merged**
