### PR TITLE
print type parameters in typedefs

### PR DESCRIPTION
**Pull request by jodinathan**
fixes https://github.com/dart-lang/code_builder/issues/402

### CODE REVIEW

**Comment by donny-dont** [comment]
I feel like the formatting parts from this PR should be removed and done in another PR.

**Comment by jodinathan** [comment]
@donny-dont even thought I followed the instructions in the README about formatting, I think the changes happened when I executed the generator.

**Comment by donny-dont** [comment]
@jodinathan I did #404 in case the maintainers here wanted a commit for just updating the generated files. It seems to have a majority of the stuff you had in your commit.

**Comment by donny-dont** [comment]
@jodinathan the changes are in just rebase your patch. If it has any problems during the rebase just fix the conflicts or default to the base branch and rerun the generation.

**Comment by donny-dont** [comment]
Its saved as a .txt file but here's a diff with your changes based on latest master.

[typedef.txt](https://github.com/dart-lang/code_builder/files/10936834/typedef.txt)

**Review by natebosch — APPROVED** [review]

**Pull request merged**
