### PR TITLE
Don't emit `new` keyword in generated code

### LINKED ISSUE #220: omit optional new in constructor calls

### PR DESCRIPTION
**Pull request by natebosch**
Closes #220

### CODE REVIEW

**Comment by natebosch** [comment]
Yeah releasing as a -dev works for me, want me to change the pubspec?

**Comment by matanlurey** [comment]
If you don't mind, thanks!

**Comment by natebosch** [comment]
Add `-dev.1` in pubpsec and changelog.

Or did you intend for this to be `4.0.0-dev.1`?

**Comment by matanlurey** [comment]
What do you think? Are there any other more visible breaking changes we want to do?

**Comment by natebosch** [comment]
Omitting `const` is tougher but we could try doing that as well.

I'm somewhat more inclined to not call this a breaking change since it's only the more brittle tests that will break - but I don't have strong opinions either way.

**Comment by matanlurey** [comment]
@natebosch Still want this?

**Comment by natebosch** [comment]
Yes, this is still worthwhile.

Renamed version to `3.2.0-alpha` to indicate non-breaking but, give a window for opting in to the alpha and updating goldens.

**Pull request merged**
