### PR TITLE
Add support for creating `mixin`s

### PR DESCRIPTION
**Pull request by donny-dont**
Redo of #263 to latest.

Added the ability to add fields to the `mixin` as well.

### CODE REVIEW

**Comment by donny-dont** [comment]
Hopefully #326 can land as well since adding fields makes more sense when you can do a `late final` field.

**Comment by donny-dont** [comment]
@natebosch could you take a look at this when you get a chance?

**Review by natebosch — APPROVED** [review]

**Comment by donny-dont** [comment]
Thanks @natebosch

**Comment by cver** [comment]
Hi, when will you release new version which supports creating `mixin`?

**Comment by donny-dont** [comment]
@cver its there since [4.1.0](https://pub.dev/packages/code_builder/changelog#410)

**Pull request merged**
